#!/usr/bin/env bash
# Cross-package coverage report. Go's default per-package coverage under-counts
# because a test in package A that exercises package B is not attributed to B; we
# use -coverpkg=./... to attribute correctly.
#
# The "production" total excludes code that is not meant to be unit-covered:
#   - internal/db          generated by sqlc
#   - api/gen              generated by buf (protoc-gen-go + protoc-gen-connect-go)
#   - internal/metadata/pg integration-only (TestContainers / Docker lane)
#   - internal/simio/real/s3.go  integration-only: the S3 wrapper is proven by the
#                          shared objectstore contract (internal/simio/objectstore/
#                          storetest) running against a real backend in a container,
#                          the same way metadata/pg is proven against real Postgres
#   - internal/testinfra   integration-only container scaffolding
#   - .../objectstore/storetest  the shared store contract: test scaffolding that
#                          every implementation runs, imported only by tests
#   - internal/metadata/metadatatest  the same, for metadata.Store: its pg half only
#                          runs in the integration lane
#   - cmd/                  main() entrypoints
#   - internal/dst         the DST test harness itself
set -euo pipefail

EXCLUDE='internal/db/|api/gen/|internal/metadata/pg/|internal/simio/real/s3.go|internal/simio/objectstore/storetest/|internal/metadata/metadatatest/|internal/testinfra/|/cmd/|internal/dst/'

# -count=1: never reuse a cached test result here. A cached entry can carry coverage
# blocks from an older compilation of a file, so the profile ends up describing two
# versions at once and the percentage depends on the cache state.
go test -count=1 -coverpkg=./... -coverprofile=cover.raw ./... >/dev/null

# Merge before measuring. With -coverpkg=./... every test binary emits the *whole*
# block set, so the same block appears once per binary — covered by the binary that
# exercises it and zero everywhere else. `go tool cover -func` treats those as
# separate entries, so the reported percentage drifts down as packages are added even
# when nothing lost coverage. Union them (mode: set => a block is covered if any
# binary covered it) so the number means what it says.
awk 'NR==1 {print; next} {key=$1; c=$3; if (!(key in seen) || c+0 > cnt[key]) {cnt[key]=c+0; stmts[key]=$2; if (!(key in seen)) order[++n]=key; seen[key]=1}}
     END {for (i=1; i<=n; i++) print order[i], stmts[order[i]], cnt[order[i]]}' cover.raw >cover.out

head -1 cover.out >cover.prod.out
grep -vE "$EXCLUDE" cover.out | tail -n +2 >>cover.prod.out

overall=$(go tool cover -func=cover.out | awk '/^total:/{print $NF}')
prod=$(go tool cover -func=cover.prod.out | awk '/^total:/{print $NF}')

echo "overall (all packages):        ${overall}"
echo "production (unit-covered code): ${prod}"

# Enforce a floor on production code.
floor=90
prod_num=${prod%\%}
if awk "BEGIN{exit !(${prod_num} < ${floor})}"; then
	echo "FAIL: production coverage ${prod} is below ${floor}%"
	exit 1
fi
echo "OK: production coverage >= ${floor}%"
