// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hosts.sql

package db

import (
	"context"
)

const getHost = `-- name: GetHost :one
SELECT host_id, state, agent_version, max_format_version, nvme_total_bytes, nvme_used_bytes, nvme_committed_bytes, last_heartbeat FROM hosts WHERE host_id = $1
`

func (q *Queries) GetHost(ctx context.Context, hostID string) (*Host, error) {
	row := q.db.QueryRow(ctx, getHost, hostID)
	var i Host
	err := row.Scan(
		&i.HostID,
		&i.State,
		&i.AgentVersion,
		&i.MaxFormatVersion,
		&i.NvmeTotalBytes,
		&i.NvmeUsedBytes,
		&i.NvmeCommittedBytes,
		&i.LastHeartbeat,
	)
	return &i, err
}

const getHostLease = `-- name: GetHostLease :one
SELECT host_id, granted_at, last_renewal, ttl_seconds FROM host_leases WHERE host_id = $1
`

func (q *Queries) GetHostLease(ctx context.Context, hostID string) (*HostLease, error) {
	row := q.db.QueryRow(ctx, getHostLease, hostID)
	var i HostLease
	err := row.Scan(
		&i.HostID,
		&i.GrantedAt,
		&i.LastRenewal,
		&i.TtlSeconds,
	)
	return &i, err
}

const renewHostLease = `-- name: RenewHostLease :execrows
WITH valid AS (
    SELECT 1 FROM control_plane_leader WHERE singleton AND term = $3
)
INSERT INTO host_leases (host_id, granted_at, last_renewal, ttl_seconds)
SELECT $1, now(), now(), $2
WHERE EXISTS (SELECT 1 FROM valid)
ON CONFLICT (host_id) DO UPDATE
  SET last_renewal = now(),
      ttl_seconds = EXCLUDED.ttl_seconds
`

type RenewHostLeaseParams struct {
	HostID     string `json:"host_id"`
	TtlSeconds int32  `json:"ttl_seconds"`
	Term       int64  `json:"term"`
}

// Grouped per-host lease renewal (§12.6), term-guarded.
func (q *Queries) RenewHostLease(ctx context.Context, arg RenewHostLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewHostLease, arg.HostID, arg.TtlSeconds, arg.Term)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertHost = `-- name: UpsertHost :execrows
WITH valid AS (
    SELECT 1 FROM control_plane_leader WHERE singleton AND term = $8
)
INSERT INTO hosts (
    host_id, state, agent_version, max_format_version,
    nvme_total_bytes, nvme_used_bytes, nvme_committed_bytes, last_heartbeat
)
SELECT $1, $2, $3, $4, $5, $6, $7, now()
WHERE EXISTS (SELECT 1 FROM valid)
ON CONFLICT (host_id) DO UPDATE
  SET state = EXCLUDED.state,
      agent_version = EXCLUDED.agent_version,
      max_format_version = EXCLUDED.max_format_version,
      nvme_total_bytes = EXCLUDED.nvme_total_bytes,
      nvme_used_bytes = EXCLUDED.nvme_used_bytes,
      nvme_committed_bytes = EXCLUDED.nvme_committed_bytes,
      last_heartbeat = now()
`

type UpsertHostParams struct {
	HostID             string `json:"host_id"`
	State              string `json:"state"`
	AgentVersion       string `json:"agent_version"`
	MaxFormatVersion   int32  `json:"max_format_version"`
	NvmeTotalBytes     int64  `json:"nvme_total_bytes"`
	NvmeUsedBytes      int64  `json:"nvme_used_bytes"`
	NvmeCommittedBytes int64  `json:"nvme_committed_bytes"`
	Term               int64  `json:"term"`
}

// Term-guarded (§7): the INSERT ... SELECT produces no row when the term is stale,
// so a zombie CP affects 0 rows.
func (q *Queries) UpsertHost(ctx context.Context, arg UpsertHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertHost,
		arg.HostID,
		arg.State,
		arg.AgentVersion,
		arg.MaxFormatVersion,
		arg.NvmeTotalBytes,
		arg.NvmeUsedBytes,
		arg.NvmeCommittedBytes,
		arg.Term,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
