// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leadership.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLeadership = `-- name: AcquireLeadership :one
INSERT INTO control_plane_leader (singleton, term, holder_id, renewed_at)
VALUES (true, 1, $1, now())
ON CONFLICT (singleton) DO UPDATE
  SET term = control_plane_leader.term + 1,
      holder_id = $1,
      renewed_at = now()
RETURNING term
`

// Take (or renew) Control Plane leadership, incrementing the term (§7).
func (q *Queries) AcquireLeadership(ctx context.Context, holderID string) (int64, error) {
	row := q.db.QueryRow(ctx, acquireLeadership, holderID)
	var term int64
	err := row.Scan(&term)
	return term, err
}

const databaseNow = `-- name: DatabaseNow :one
SELECT now()::timestamptz
`

// The database's own clock. Every fencing deadline is derived from a timestamp this
// clock stamped (host_leases.last_renewal), so the Control Plane compares against
// this rather than against its own wall clock: a container clock that jumps forward
// would otherwise shorten the fencing wait by exactly that offset (§12.1).
func (q *Queries) DatabaseNow(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, databaseNow)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const getLeader = `-- name: GetLeader :one
SELECT term, holder_id, renewed_at
FROM control_plane_leader
WHERE singleton
`

type GetLeaderRow struct {
	Term      int64              `json:"term"`
	HolderID  string             `json:"holder_id"`
	RenewedAt pgtype.Timestamptz `json:"renewed_at"`
}

func (q *Queries) GetLeader(ctx context.Context) (*GetLeaderRow, error) {
	row := q.db.QueryRow(ctx, getLeader)
	var i GetLeaderRow
	err := row.Scan(&i.Term, &i.HolderID, &i.RenewedAt)
	return &i, err
}

const renewLeadership = `-- name: RenewLeadership :execrows
UPDATE control_plane_leader
   SET renewed_at = now()
 WHERE singleton
   AND term = $1
   AND holder_id = $2
`

type RenewLeadershipParams struct {
	Term     int64  `json:"term"`
	HolderID string `json:"holder_id"`
}

// Say "still here" without becoming a new leader (§7). The term and the holder are
// both predicates and neither is written: this is the one leadership write that must
// not move the term, because every admin one-shot in cmd/control-plane reads GetLeader
// and then writes under the term it read.
//
// 0 rows is the whole point of the guard. It means this process is no longer the
// leader — superseded by an election, or running against a database that was restored
// underneath it — and the caller's answer to that is to exit, not to retry.
func (q *Queries) RenewLeadership(ctx context.Context, arg RenewLeadershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewLeadership, arg.Term, arg.HolderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
