// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leadership.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLeadership = `-- name: AcquireLeadership :one
INSERT INTO control_plane_leader (singleton, term, holder_id, renewed_at)
VALUES (true, 1, $1, now())
ON CONFLICT (singleton) DO UPDATE
  SET term = control_plane_leader.term + 1,
      holder_id = $1,
      renewed_at = now()
RETURNING term
`

// Take (or renew) Control Plane leadership, incrementing the term (§7).
func (q *Queries) AcquireLeadership(ctx context.Context, holderID string) (int64, error) {
	row := q.db.QueryRow(ctx, acquireLeadership, holderID)
	var term int64
	err := row.Scan(&term)
	return term, err
}

const getLeader = `-- name: GetLeader :one
SELECT term, holder_id, renewed_at
FROM control_plane_leader
WHERE singleton
`

type GetLeaderRow struct {
	Term      int64              `json:"term"`
	HolderID  string             `json:"holder_id"`
	RenewedAt pgtype.Timestamptz `json:"renewed_at"`
}

func (q *Queries) GetLeader(ctx context.Context) (*GetLeaderRow, error) {
	row := q.db.QueryRow(ctx, getLeader)
	var i GetLeaderRow
	err := row.Scan(&i.Term, &i.HolderID, &i.RenewedAt)
	return &i, err
}
