// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ControlPlaneLeader struct {
	Singleton bool               `json:"singleton"`
	Term      int64              `json:"term"`
	HolderID  string             `json:"holder_id"`
	RenewedAt pgtype.Timestamptz `json:"renewed_at"`
}

type Host struct {
	HostID                 uuid.UUID          `json:"host_id"`
	State                  string             `json:"state"`
	CordonReason           string             `json:"cordon_reason"`
	AgentVersion           string             `json:"agent_version"`
	MaxFormatVersion       int32              `json:"max_format_version"`
	NvmeTotalBytes         int64              `json:"nvme_total_bytes"`
	NvmeUsedBytes          int64              `json:"nvme_used_bytes"`
	NvmeRemoteBacklogBytes int64              `json:"nvme_remote_backlog_bytes"`
	LastHeartbeat          pgtype.Timestamptz `json:"last_heartbeat"`
}

type HostCommittedByte struct {
	HostID         uuid.UUID `json:"host_id"`
	CommittedBytes int64     `json:"committed_bytes"`
}

type HostLease struct {
	HostID      uuid.UUID          `json:"host_id"`
	GrantedAt   pgtype.Timestamptz `json:"granted_at"`
	LastRenewal pgtype.Timestamptz `json:"last_renewal"`
	TtlSeconds  int32              `json:"ttl_seconds"`
}

type Snapshot struct {
	SnapshotID       uuid.UUID          `json:"snapshot_id"`
	VolumeID         uuid.UUID          `json:"volume_id"`
	ParentSnapshotID pgtype.UUID        `json:"parent_snapshot_id"`
	Epoch            int64              `json:"epoch"`
	CommitID         pgtype.UUID        `json:"commit_id"`
	SourceHostID     pgtype.UUID        `json:"source_host_id"`
	State            string             `json:"state"`
	Portable         bool               `json:"portable"`
	RequestID        uuid.UUID          `json:"request_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Volume struct {
	VolumeID              uuid.UUID          `json:"volume_id"`
	SizeBytes             int64              `json:"size_bytes"`
	BlockSize             int32              `json:"block_size"`
	RpoTargetSeconds      int32              `json:"rpo_target_seconds"`
	CurrentEpoch          int64              `json:"current_epoch"`
	State                 string             `json:"state"`
	PrimaryHostID         pgtype.UUID        `json:"primary_host_id"`
	StandbyHostID         pgtype.UUID        `json:"standby_host_id"`
	ChainDepth            int32              `json:"chain_depth"`
	ParentSnapshotID      pgtype.UUID        `json:"parent_snapshot_id"`
	DekWrapped            []byte             `json:"dek_wrapped"`
	KekID                 string             `json:"kek_id"`
	DekKeyID              int64              `json:"dek_key_id"`
	HeadCommitID          pgtype.UUID        `json:"head_commit_id"`
	CommitAgeSeconds      pgtype.Int4        `json:"commit_age_seconds"`
	UnpublishedLocalBytes int64              `json:"unpublished_local_bytes"`
	ReportedAt            pgtype.Timestamptz `json:"reported_at"`
	Refusal               string             `json:"refusal"`
	RefusalDetail         string             `json:"refusal_detail"`
	FencingStartedAt      pgtype.Timestamptz `json:"fencing_started_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
