// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ControlPlaneLeader struct {
	Singleton bool               `json:"singleton"`
	Term      int64              `json:"term"`
	HolderID  string             `json:"holder_id"`
	RenewedAt pgtype.Timestamptz `json:"renewed_at"`
}

type Host struct {
	HostID                 uuid.UUID          `json:"host_id"`
	State                  string             `json:"state"`
	AgentVersion           string             `json:"agent_version"`
	MaxFormatVersion       int32              `json:"max_format_version"`
	NvmeTotalBytes         int64              `json:"nvme_total_bytes"`
	NvmeUsedBytes          int64              `json:"nvme_used_bytes"`
	NvmeRemoteBacklogBytes int64              `json:"nvme_remote_backlog_bytes"`
	LastHeartbeat          pgtype.Timestamptz `json:"last_heartbeat"`
	RenewalsBlockedUntil   pgtype.Timestamptz `json:"renewals_blocked_until"`
}

type HostCommittedByte struct {
	HostID         uuid.UUID `json:"host_id"`
	CommittedBytes int64     `json:"committed_bytes"`
}

type HostLease struct {
	HostID      uuid.UUID          `json:"host_id"`
	GrantedAt   pgtype.Timestamptz `json:"granted_at"`
	LastRenewal pgtype.Timestamptz `json:"last_renewal"`
	TtlSeconds  int32              `json:"ttl_seconds"`
}

type Operation struct {
	OperationID  uuid.UUID          `json:"operation_id"`
	Kind         string             `json:"kind"`
	VolumeID     pgtype.UUID        `json:"volume_id"`
	HostID       pgtype.UUID        `json:"host_id"`
	DesiredState []byte             `json:"desired_state"`
	CurrentState []byte             `json:"current_state"`
	Phase        string             `json:"phase"`
	Error        pgtype.Text        `json:"error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Snapshot struct {
	SnapshotID       uuid.UUID          `json:"snapshot_id"`
	VolumeID         uuid.UUID          `json:"volume_id"`
	ParentSnapshotID pgtype.UUID        `json:"parent_snapshot_id"`
	Epoch            int64              `json:"epoch"`
	TargetSequence   int64              `json:"target_sequence"`
	RootDigest       string             `json:"root_digest"`
	SourceHostID     pgtype.UUID        `json:"source_host_id"`
	State            string             `json:"state"`
	Portable         bool               `json:"portable"`
	ManifestKey      pgtype.Text        `json:"manifest_key"`
	RequestID        uuid.UUID          `json:"request_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Volume struct {
	VolumeID          uuid.UUID          `json:"volume_id"`
	SizeBytes         int64              `json:"size_bytes"`
	Durability        string             `json:"durability"`
	BlockSize         int32              `json:"block_size"`
	CurrentEpoch      int64              `json:"current_epoch"`
	State             string             `json:"state"`
	PrimaryHostID     pgtype.UUID        `json:"primary_host_id"`
	StandbyHostID     pgtype.UUID        `json:"standby_host_id"`
	ActiveRootID      pgtype.UUID        `json:"active_root_id"`
	PublishedRootID   pgtype.UUID        `json:"published_root_id"`
	ChainDepth        int32              `json:"chain_depth"`
	ParentSnapshotID  pgtype.UUID        `json:"parent_snapshot_id"`
	DekWrapped        []byte             `json:"dek_wrapped"`
	KekID             string             `json:"kek_id"`
	DekKeyID          int64              `json:"dek_key_id"`
	LocalSequence     int64              `json:"local_sequence"`
	DurableSequence   int64              `json:"durable_sequence"`
	PublishedSequence int64              `json:"published_sequence"`
	FencingStartedAt  pgtype.Timestamptz `json:"fencing_started_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
