// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOperation = `-- name: GetOperation :one
SELECT operation_id, kind, volume_id, host_id, desired_state, current_state, phase, error, created_at, updated_at FROM operations WHERE operation_id = $1
`

func (q *Queries) GetOperation(ctx context.Context, operationID uuid.UUID) (*Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, operationID)
	var i Operation
	err := row.Scan(
		&i.OperationID,
		&i.Kind,
		&i.VolumeID,
		&i.HostID,
		&i.DesiredState,
		&i.CurrentState,
		&i.Phase,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const recordOperation = `-- name: RecordOperation :execrows
INSERT INTO operations (operation_id, kind, volume_id, host_id, desired_state, current_state, phase)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (operation_id) DO NOTHING
`

type RecordOperationParams struct {
	OperationID  uuid.UUID   `json:"operation_id"`
	Kind         string      `json:"kind"`
	VolumeID     pgtype.UUID `json:"volume_id"`
	HostID       pgtype.UUID `json:"host_id"`
	DesiredState []byte      `json:"desired_state"`
	CurrentState []byte      `json:"current_state"`
	Phase        string      `json:"phase"`
}

// Admin idempotency by request_id (§18). Returns 1 if newly recorded, 0 if the
// operation_id already existed (a duplicate request).
func (q *Queries) RecordOperation(ctx context.Context, arg RecordOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordOperation,
		arg.OperationID,
		arg.Kind,
		arg.VolumeID,
		arg.HostID,
		arg.DesiredState,
		arg.CurrentState,
		arg.Phase,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOperationPhase = `-- name: UpdateOperationPhase :execrows
UPDATE operations
   SET current_state = $2, phase = $3, error = $4, updated_at = now()
 WHERE operation_id = $1
   AND phase = ANY($5::text[])
`

type UpdateOperationPhaseParams struct {
	OperationID   uuid.UUID   `json:"operation_id"`
	CurrentState  []byte      `json:"current_state"`
	Phase         string      `json:"phase"`
	Error         pgtype.Text `json:"error"`
	AllowedPhases []string    `json:"allowed_phases"`
}

// Transition-guarded (§7): $5 is the set of phases that may legally become $3, so a
// terminal operation cannot be resurrected even by a buggy caller.
func (q *Queries) UpdateOperationPhase(ctx context.Context, arg UpdateOperationPhaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOperationPhase,
		arg.OperationID,
		arg.CurrentState,
		arg.Phase,
		arg.Error,
		arg.AllowedPhases,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
