// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOperation = `-- name: GetOperation :one
SELECT operation_id, kind, volume_id, host_id, desired_state, current_state, phase, error, created_at, updated_at FROM operations WHERE operation_id = $1
`

func (q *Queries) GetOperation(ctx context.Context, operationID uuid.UUID) (*Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, operationID)
	var i Operation
	err := row.Scan(
		&i.OperationID,
		&i.Kind,
		&i.VolumeID,
		&i.HostID,
		&i.DesiredState,
		&i.CurrentState,
		&i.Phase,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listLiveOperationsByHost = `-- name: ListLiveOperationsByHost :many
SELECT operation_id, kind, volume_id, host_id, desired_state, current_state, phase, error, created_at, updated_at FROM operations
 WHERE host_id = $1
   AND phase NOT IN ('SUCCEEDED', 'CANCELED')
 ORDER BY operation_id
`

// The operations still happening on a host, so a reconciler can ask what is already
// under way before starting something else (§7, §28.1). Deterministic order: the
// answer must not depend on row order (INV-02).
//
// The phase predicate is written out rather than passed as a parameter because it is
// what makes operations_live_by_host_idx usable: the planner has to see that the
// query's condition implies the index's, and a parameter it cannot see is a
// condition it cannot match. `operations` is append-only history — nothing deletes a
// finished operation — so without the partial index this walks everything the host
// has ever done, on every drain pass.
//
// It is the terminal set spelled out, which lifecycle.OperationPhase.Terminal() also
// defines; TestPGLivePhaseSetsAgreeWithTheLifecycle refuses to let the two drift.
func (q *Queries) ListLiveOperationsByHost(ctx context.Context, hostID pgtype.UUID) ([]*Operation, error) {
	rows, err := q.db.Query(ctx, listLiveOperationsByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.OperationID,
			&i.Kind,
			&i.VolumeID,
			&i.HostID,
			&i.DesiredState,
			&i.CurrentState,
			&i.Phase,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordOperation = `-- name: RecordOperation :execrows
WITH valid AS (
    SELECT 1 FROM control_plane_leader WHERE singleton AND term = $8
)
INSERT INTO operations (operation_id, kind, volume_id, host_id, desired_state, current_state, phase)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE EXISTS (SELECT 1 FROM valid)
ON CONFLICT (operation_id) DO NOTHING
`

type RecordOperationParams struct {
	OperationID  uuid.UUID   `json:"operation_id"`
	Kind         string      `json:"kind"`
	VolumeID     pgtype.UUID `json:"volume_id"`
	HostID       pgtype.UUID `json:"host_id"`
	DesiredState []byte      `json:"desired_state"`
	CurrentState []byte      `json:"current_state"`
	Phase        string      `json:"phase"`
	Term         int64       `json:"term"`
}

// Admin idempotency by request_id (§18) + term guard (§7): the INSERT ... SELECT
// produces no row for a stale term, so a zombie CP cannot record work. Returns 1 if
// newly recorded, 0 if the operation_id already existed or the term is stale.
func (q *Queries) RecordOperation(ctx context.Context, arg RecordOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordOperation,
		arg.OperationID,
		arg.Kind,
		arg.VolumeID,
		arg.HostID,
		arg.DesiredState,
		arg.CurrentState,
		arg.Phase,
		arg.Term,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOperationPhase = `-- name: UpdateOperationPhase :execrows
UPDATE operations
   SET current_state = $2, phase = $3, error = $4, updated_at = now()
 WHERE operations.operation_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $5
   AND operations.phase = ANY($6::text[])
   -- The derived value is the host_committed_bytes view; schema.sql says why it is
   -- a view and what it sums. A bound naming a host nobody registered admits
   -- nothing: no row in the view, a NULL comparison, no write.
   AND ($7::uuid IS NULL
       OR (EXISTS (SELECT 1 FROM hosts
                    WHERE host_id = $7::uuid
                      AND nvme_used_bytes <= $8::bigint)
           AND (SELECT c.committed_bytes FROM host_committed_bytes c
                 WHERE c.host_id = $7::uuid)
               + $9::bigint <= $10::bigint))
`

type UpdateOperationPhaseParams struct {
	OperationID    uuid.UUID   `json:"operation_id"`
	CurrentState   []byte      `json:"current_state"`
	Phase          string      `json:"phase"`
	Error          pgtype.Text `json:"error"`
	Term           int64       `json:"term"`
	AllowedPhases  []string    `json:"allowed_phases"`
	BoundHost      pgtype.UUID `json:"bound_host"`
	BoundUsedLimit int64       `json:"bound_used_limit"`
	BoundAddBytes  int64       `json:"bound_add_bytes"`
	BoundLimit     int64       `json:"bound_limit"`
}

// Transition-guarded (§7): $5 is the set of phases that may legally become $3, so a
// terminal operation cannot be resurrected even by a buggy caller.
//
// It also carries the capacity bound (ADR-0017), because an operation's recorded
// progress *is* its reservation: the plan entry a drain writes here is what charges
// the destination for a volume that is not primary there yet. The bound is
// evaluated against the derived value as it stands before this write, plus the bytes
// this write is about to reserve, so two operations that chose the same destination
// against the same fleet read produce one reservation and one ErrCapacityExceeded.
// Its second arm is the destination's own measurement of its device (ADR-0013): a
// drain that evacuates a host must not fill the next one, and being inside the
// §28.2 promises says nothing about that — volumes.sql carries the reasoning.
// A write with no bound reserves nothing new (a progress save, a phase change).
// The outer column references are qualified because the capacity predicate below
// reads `operations` again (every in-flight plan, this one included): unqualified
// `operation_id` would then be ambiguous.
func (q *Queries) UpdateOperationPhase(ctx context.Context, arg UpdateOperationPhaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOperationPhase,
		arg.OperationID,
		arg.CurrentState,
		arg.Phase,
		arg.Error,
		arg.Term,
		arg.AllowedPhases,
		arg.BoundHost,
		arg.BoundUsedLimit,
		arg.BoundAddBytes,
		arg.BoundLimit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
