// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOperation = `-- name: GetOperation :one
SELECT operation_id, kind, volume_id, host_id, desired_state, current_state, phase, error, created_at, updated_at FROM operations WHERE operation_id = $1
`

func (q *Queries) GetOperation(ctx context.Context, operationID uuid.UUID) (*Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, operationID)
	var i Operation
	err := row.Scan(
		&i.OperationID,
		&i.Kind,
		&i.VolumeID,
		&i.HostID,
		&i.DesiredState,
		&i.CurrentState,
		&i.Phase,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listOperationsByHost = `-- name: ListOperationsByHost :many
SELECT operation_id, kind, volume_id, host_id, desired_state, current_state, phase, error, created_at, updated_at FROM operations WHERE host_id = $1 ORDER BY operation_id
`

// Every operation recorded against a host, so a reconciler can ask what is already
// happening to it before starting something else (§7, §28.1). Deterministic order:
// the answer must not depend on row order (INV-02), and the composite index
// operations (host_id, operation_id) satisfies both the filter and the sort.
func (q *Queries) ListOperationsByHost(ctx context.Context, hostID pgtype.UUID) ([]*Operation, error) {
	rows, err := q.db.Query(ctx, listOperationsByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.OperationID,
			&i.Kind,
			&i.VolumeID,
			&i.HostID,
			&i.DesiredState,
			&i.CurrentState,
			&i.Phase,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordOperation = `-- name: RecordOperation :execrows
WITH valid AS (
    SELECT 1 FROM control_plane_leader WHERE singleton AND term = $8
)
INSERT INTO operations (operation_id, kind, volume_id, host_id, desired_state, current_state, phase)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE EXISTS (SELECT 1 FROM valid)
ON CONFLICT (operation_id) DO NOTHING
`

type RecordOperationParams struct {
	OperationID  uuid.UUID   `json:"operation_id"`
	Kind         string      `json:"kind"`
	VolumeID     pgtype.UUID `json:"volume_id"`
	HostID       pgtype.UUID `json:"host_id"`
	DesiredState []byte      `json:"desired_state"`
	CurrentState []byte      `json:"current_state"`
	Phase        string      `json:"phase"`
	Term         int64       `json:"term"`
}

// Admin idempotency by request_id (§18) + term guard (§7): the INSERT ... SELECT
// produces no row for a stale term, so a zombie CP cannot record work. Returns 1 if
// newly recorded, 0 if the operation_id already existed or the term is stale.
func (q *Queries) RecordOperation(ctx context.Context, arg RecordOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordOperation,
		arg.OperationID,
		arg.Kind,
		arg.VolumeID,
		arg.HostID,
		arg.DesiredState,
		arg.CurrentState,
		arg.Phase,
		arg.Term,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOperationPhase = `-- name: UpdateOperationPhase :execrows
UPDATE operations
   SET current_state = $2, phase = $3, error = $4, updated_at = now()
 WHERE operations.operation_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $5
   AND operations.phase = ANY($6::text[])
   -- The derived value is the host_committed_bytes view; schema.sql says why it is
   -- a view and what it sums. A bound naming a host nobody registered admits
   -- nothing: no row in the view, a NULL comparison, no write.
   AND ($7::uuid IS NULL
       OR (EXISTS (SELECT 1 FROM hosts WHERE host_id = $7::uuid)
           AND (SELECT c.committed_bytes FROM host_committed_bytes c
                 WHERE c.host_id = $7::uuid)
               + $8::bigint <= $9::bigint))
`

type UpdateOperationPhaseParams struct {
	OperationID   uuid.UUID   `json:"operation_id"`
	CurrentState  []byte      `json:"current_state"`
	Phase         string      `json:"phase"`
	Error         pgtype.Text `json:"error"`
	Term          int64       `json:"term"`
	AllowedPhases []string    `json:"allowed_phases"`
	BoundHost     pgtype.UUID `json:"bound_host"`
	BoundAddBytes int64       `json:"bound_add_bytes"`
	BoundLimit    int64       `json:"bound_limit"`
}

// Transition-guarded (§7): $5 is the set of phases that may legally become $3, so a
// terminal operation cannot be resurrected even by a buggy caller.
//
// It also carries the §28.2 oversubscription bound (ADR-0017), because an operation's
// recorded progress *is* its reservation: the plan entry a drain writes here is what
// charges the destination for a volume that is not primary there yet. The bound is
// evaluated against the derived value as it stands before this write, plus the bytes
// this write is about to reserve, so two operations that chose the same destination
// against the same fleet read produce one reservation and one ErrCapacityExceeded.
// A write with no bound reserves nothing new (a progress save, a phase change).
// The outer column references are qualified because the capacity predicate below
// reads `operations` again (every in-flight plan, this one included): unqualified
// `operation_id` would then be ambiguous.
func (q *Queries) UpdateOperationPhase(ctx context.Context, arg UpdateOperationPhaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOperationPhase,
		arg.OperationID,
		arg.CurrentState,
		arg.Phase,
		arg.Error,
		arg.Term,
		arg.AllowedPhases,
		arg.BoundHost,
		arg.BoundAddBytes,
		arg.BoundLimit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
