// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSnapshot = `-- name: CreateSnapshot :execrows
WITH valid AS (
    SELECT 1 FROM control_plane_leader WHERE singleton AND term = $8
)
INSERT INTO snapshots (
    snapshot_id, volume_id, parent_snapshot_id, epoch,
    commit_id, source_host_id, state, request_id
)
SELECT $1, $2, $3, $4, $9::uuid, $5, $6, $7
WHERE EXISTS (SELECT 1 FROM valid)
ON CONFLICT DO NOTHING
`

type CreateSnapshotParams struct {
	SnapshotID       uuid.UUID   `json:"snapshot_id"`
	VolumeID         uuid.UUID   `json:"volume_id"`
	ParentSnapshotID pgtype.UUID `json:"parent_snapshot_id"`
	Epoch            int64       `json:"epoch"`
	SourceHostID     pgtype.UUID `json:"source_host_id"`
	State            string      `json:"state"`
	RequestID        uuid.UUID   `json:"request_id"`
	Term             int64       `json:"term"`
	CommitID         pgtype.UUID `json:"commit_id"`
}

// Term-guarded snapshot record (§19).
// INV-16: a snapshot is immutable once it is in the catalog, so a duplicate record
// — a retried request, or two operators rebuilding at once — is a no-op rather than
// an overwrite or a 23505 that aborts the rebuild half-way. Untargeted, so the
// request_id uniqueness (§18 idempotency) is covered too. 0 rows is ambiguous
// between "already there" and "stale term"; the adapter disambiguates.
func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSnapshot,
		arg.SnapshotID,
		arg.VolumeID,
		arg.ParentSnapshotID,
		arg.Epoch,
		arg.SourceHostID,
		arg.State,
		arg.RequestID,
		arg.Term,
		arg.CommitID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT snapshot_id, volume_id, parent_snapshot_id, epoch, commit_id, source_host_id, state, portable, request_id, created_at FROM snapshots WHERE snapshot_id = $1
`

func (q *Queries) GetSnapshot(ctx context.Context, snapshotID uuid.UUID) (*Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshot, snapshotID)
	var i Snapshot
	err := row.Scan(
		&i.SnapshotID,
		&i.VolumeID,
		&i.ParentSnapshotID,
		&i.Epoch,
		&i.CommitID,
		&i.SourceHostID,
		&i.State,
		&i.Portable,
		&i.RequestID,
		&i.CreatedAt,
	)
	return &i, err
}

const listPendingSnapshots = `-- name: ListPendingSnapshots :many
SELECT s.snapshot_id, s.volume_id, s.parent_snapshot_id, s.epoch, s.commit_id, s.source_host_id, s.state, s.portable, s.request_id, s.created_at FROM snapshots s
  JOIN volumes v ON v.volume_id = s.volume_id
 WHERE v.primary_host_id = $1
   AND s.state = 'CREATING'
 ORDER BY s.snapshot_id
`

type ListPendingSnapshotsRow struct {
	Snapshot Snapshot `json:"snapshot"`
}

// The snapshots a host has been asked to take (§19), for the desired state it is
// handed. Joined through volumes rather than filtered on snapshots.source_host_id,
// because the request names a *volume*: whichever host serves it when the request is
// picked up is the one that can freeze it, and source_host_id is stamped on
// completion by the host that actually did — which is what §20's placement rule 1
// later reads.
//
// Ordered by snapshot_id so a host with several outstanding takes them oldest first
// (UUIDv7 is time-ordered, INV-22) and two Control Planes answer identically (INV-02).
func (q *Queries) ListPendingSnapshots(ctx context.Context, primaryHostID pgtype.UUID) ([]*ListPendingSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listPendingSnapshots, primaryHostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListPendingSnapshotsRow{}
	for rows.Next() {
		var i ListPendingSnapshotsRow
		if err := rows.Scan(
			&i.Snapshot.SnapshotID,
			&i.Snapshot.VolumeID,
			&i.Snapshot.ParentSnapshotID,
			&i.Snapshot.Epoch,
			&i.Snapshot.CommitID,
			&i.Snapshot.SourceHostID,
			&i.Snapshot.State,
			&i.Snapshot.Portable,
			&i.Snapshot.RequestID,
			&i.Snapshot.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedSnapshots = `-- name: ListUnfinishedSnapshots :many
SELECT snapshot_id, volume_id, parent_snapshot_id, epoch, commit_id, source_host_id, state, portable, request_id, created_at FROM snapshots
 WHERE state = ANY($1::text[])
 ORDER BY snapshot_id
`

// The snapshots nothing has closed out, fleet-wide, for a human reading the catalog.
//
// The states come in as an array rather than being written here, the same move
// SetSnapshotState makes with allowed_states: the §19 vocabulary's authority is
// internal/lifecycle (SnapshotState.Unfinished), and a literal IN-list in SQL is a
// second copy of a rule that would silently stop matching the day a state is added.
//
// No index, deliberately. This is unfiltered by host on purpose — the stuck snapshot
// is exactly the one whose volume has no primary, so ListPendingSnapshots's join
// through volumes cannot return it — and an index on `state` would be maintained by
// every snapshot write for the benefit of a query an operator runs by hand during an
// incident. Add one when something on the data path asks this question, which is a
// change to what this query is for, not a tuning.
func (q *Queries) ListUnfinishedSnapshots(ctx context.Context, states []string) ([]*Snapshot, error) {
	rows, err := q.db.Query(ctx, listUnfinishedSnapshots, states)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.SnapshotID,
			&i.VolumeID,
			&i.ParentSnapshotID,
			&i.Epoch,
			&i.CommitID,
			&i.SourceHostID,
			&i.State,
			&i.Portable,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishSnapshot = `-- name: PublishSnapshot :execrows
UPDATE snapshots
   SET state = 'PUBLISHED',
       commit_id = $2,
       source_host_id = $3
 WHERE snapshot_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $4
   AND state = 'CREATING'
`

type PublishSnapshotParams struct {
	SnapshotID   uuid.UUID   `json:"snapshot_id"`
	CommitID     pgtype.UUID `json:"commit_id"`
	SourceHostID pgtype.UUID `json:"source_host_id"`
	Term         int64       `json:"term"`
}

// CREATING → PUBLISHED, stamping the two facts only the host that took it knows: the
// commit its history is named by, and which host reported it. The manifest key is not
// among them and must not be: it is derived from the commit id (commit.ManifestKey), so
// believing a string the Agent sent is how a catalog and a bucket come to disagree about
// where a snapshot lives.
// Term-guarded, and guarded on CREATING so a report replayed after the snapshot has
// moved on cannot resurrect it (INV-16: PUBLISHED never changes).
func (q *Queries) PublishSnapshot(ctx context.Context, arg PublishSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishSnapshot,
		arg.SnapshotID,
		arg.CommitID,
		arg.SourceHostID,
		arg.Term,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSnapshotState = `-- name: SetSnapshotState :execrows
UPDATE snapshots
   SET state = $2
 WHERE snapshot_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $3
   AND state = ANY($4::text[])
`

type SetSnapshotStateParams struct {
	SnapshotID    uuid.UUID `json:"snapshot_id"`
	State         string    `json:"state"`
	Term          int64     `json:"term"`
	AllowedStates []string  `json:"allowed_states"`
}

// The §19 lifecycle (CREATING → PUBLISHED | FAILED → DELETING), term-guarded and
// transition-guarded in the predicate: $3 is the set of states that may legally
// become $2. Without this a snapshot whose publication crashed stays CREATING
// forever and the catalog side of GC never sees it.
func (q *Queries) SetSnapshotState(ctx context.Context, arg SetSnapshotStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSnapshotState,
		arg.SnapshotID,
		arg.State,
		arg.Term,
		arg.AllowedStates,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
