// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSnapshot = `-- name: CreateSnapshot :execrows
WITH valid AS (
    SELECT 1 FROM control_plane_leader WHERE singleton AND term = $11
)
INSERT INTO snapshots (
    snapshot_id, volume_id, parent_snapshot_id, epoch, target_sequence,
    root_digest, source_host_id, state, manifest_key, request_id
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
WHERE EXISTS (SELECT 1 FROM valid)
ON CONFLICT DO NOTHING
`

type CreateSnapshotParams struct {
	SnapshotID       uuid.UUID   `json:"snapshot_id"`
	VolumeID         uuid.UUID   `json:"volume_id"`
	ParentSnapshotID pgtype.UUID `json:"parent_snapshot_id"`
	Epoch            int64       `json:"epoch"`
	TargetSequence   int64       `json:"target_sequence"`
	RootDigest       string      `json:"root_digest"`
	SourceHostID     pgtype.UUID `json:"source_host_id"`
	State            string      `json:"state"`
	ManifestKey      pgtype.Text `json:"manifest_key"`
	RequestID        uuid.UUID   `json:"request_id"`
	Term             int64       `json:"term"`
}

// Term-guarded snapshot record (§19).
// INV-16: a snapshot is immutable once it is in the catalog, so a duplicate record
// — a retried request, or two operators rebuilding at once — is a no-op rather than
// an overwrite or a 23505 that aborts the rebuild half-way. Untargeted, so the
// request_id uniqueness (§18 idempotency) is covered too. 0 rows is ambiguous
// between "already there" and "stale term"; the adapter disambiguates.
func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSnapshot,
		arg.SnapshotID,
		arg.VolumeID,
		arg.ParentSnapshotID,
		arg.Epoch,
		arg.TargetSequence,
		arg.RootDigest,
		arg.SourceHostID,
		arg.State,
		arg.ManifestKey,
		arg.RequestID,
		arg.Term,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT snapshot_id, volume_id, parent_snapshot_id, epoch, target_sequence, root_digest, source_host_id, state, portable, manifest_key, request_id, created_at FROM snapshots WHERE snapshot_id = $1
`

func (q *Queries) GetSnapshot(ctx context.Context, snapshotID uuid.UUID) (*Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshot, snapshotID)
	var i Snapshot
	err := row.Scan(
		&i.SnapshotID,
		&i.VolumeID,
		&i.ParentSnapshotID,
		&i.Epoch,
		&i.TargetSequence,
		&i.RootDigest,
		&i.SourceHostID,
		&i.State,
		&i.Portable,
		&i.ManifestKey,
		&i.RequestID,
		&i.CreatedAt,
	)
	return &i, err
}

const setSnapshotState = `-- name: SetSnapshotState :execrows
UPDATE snapshots
   SET state = $2
 WHERE snapshot_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $3
   AND state = ANY($4::text[])
`

type SetSnapshotStateParams struct {
	SnapshotID    uuid.UUID `json:"snapshot_id"`
	State         string    `json:"state"`
	Term          int64     `json:"term"`
	AllowedStates []string  `json:"allowed_states"`
}

// The §19 lifecycle (CREATING → PUBLISHED | FAILED → DELETING), term-guarded and
// transition-guarded in the predicate: $3 is the set of states that may legally
// become $2. Without this a snapshot whose publication crashed stays CREATING
// forever and the catalog side of GC never sees it.
func (q *Queries) SetSnapshotState(ctx context.Context, arg SetSnapshotStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSnapshotState,
		arg.SnapshotID,
		arg.State,
		arg.Term,
		arg.AllowedStates,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
