// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: volumes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpVolumeEpoch = `-- name: BumpVolumeEpoch :one
UPDATE volumes
   SET current_epoch = current_epoch + 1,
       primary_host_id = $2,
       updated_at = now()
 WHERE volume_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $3
RETURNING current_epoch
`

type BumpVolumeEpochParams struct {
	VolumeID      uuid.UUID   `json:"volume_id"`
	PrimaryHostID pgtype.UUID `json:"primary_host_id"`
	Term          int64       `json:"term"`
}

// Increment the epoch and set the primary host, term-guarded. Returns 0 rows if
// the term is stale or the volume is missing (§12.3).
func (q *Queries) BumpVolumeEpoch(ctx context.Context, arg BumpVolumeEpochParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpVolumeEpoch, arg.VolumeID, arg.PrimaryHostID, arg.Term)
	var current_epoch int64
	err := row.Scan(&current_epoch)
	return current_epoch, err
}

const createVolume = `-- name: CreateVolume :execrows
WITH valid AS (
    SELECT 1 FROM control_plane_leader WHERE singleton AND term = $8
)
INSERT INTO volumes (volume_id, size_bytes, durability, block_size, state, dek_wrapped, kek_id)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE EXISTS (SELECT 1 FROM valid)
`

type CreateVolumeParams struct {
	VolumeID   uuid.UUID `json:"volume_id"`
	SizeBytes  int64     `json:"size_bytes"`
	Durability string    `json:"durability"`
	BlockSize  int32     `json:"block_size"`
	State      string    `json:"state"`
	DekWrapped []byte    `json:"dek_wrapped"`
	KekID      string    `json:"kek_id"`
	Term       int64     `json:"term"`
}

// Term-guarded create (§7).
func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (int64, error) {
	result, err := q.db.Exec(ctx, createVolume,
		arg.VolumeID,
		arg.SizeBytes,
		arg.Durability,
		arg.BlockSize,
		arg.State,
		arg.DekWrapped,
		arg.KekID,
		arg.Term,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVolume = `-- name: GetVolume :one
SELECT volume_id, size_bytes, durability, block_size, current_epoch, state, primary_host_id, standby_host_id, active_root_id, published_root_id, chain_depth, dek_wrapped, kek_id, local_sequence, durable_sequence, published_sequence, created_at, updated_at FROM volumes WHERE volume_id = $1
`

func (q *Queries) GetVolume(ctx context.Context, volumeID uuid.UUID) (*Volume, error) {
	row := q.db.QueryRow(ctx, getVolume, volumeID)
	var i Volume
	err := row.Scan(
		&i.VolumeID,
		&i.SizeBytes,
		&i.Durability,
		&i.BlockSize,
		&i.CurrentEpoch,
		&i.State,
		&i.PrimaryHostID,
		&i.StandbyHostID,
		&i.ActiveRootID,
		&i.PublishedRootID,
		&i.ChainDepth,
		&i.DekWrapped,
		&i.KekID,
		&i.LocalSequence,
		&i.DurableSequence,
		&i.PublishedSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateVolumeWatermarks = `-- name: UpdateVolumeWatermarks :execrows
UPDATE volumes
   SET local_sequence = $2,
       durable_sequence = $3,
       published_sequence = $4,
       updated_at = now()
 WHERE volume_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $5
`

type UpdateVolumeWatermarksParams struct {
	VolumeID          uuid.UUID `json:"volume_id"`
	LocalSequence     int64     `json:"local_sequence"`
	DurableSequence   int64     `json:"durable_sequence"`
	PublishedSequence int64     `json:"published_sequence"`
	Term              int64     `json:"term"`
}

// Lazy, informative watermark update (§5.8, §12.6), term-guarded.
func (q *Queries) UpdateVolumeWatermarks(ctx context.Context, arg UpdateVolumeWatermarksParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVolumeWatermarks,
		arg.VolumeID,
		arg.LocalSequence,
		arg.DurableSequence,
		arg.PublishedSequence,
		arg.Term,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
