// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: volumes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpVolumeEpoch = `-- name: BumpVolumeEpoch :one
UPDATE volumes
   SET current_epoch = current_epoch + 1,
       primary_host_id = $2,
       updated_at = now()
 WHERE volume_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $3
   AND current_epoch = $4
RETURNING current_epoch
`

type BumpVolumeEpochParams struct {
	VolumeID      uuid.UUID   `json:"volume_id"`
	PrimaryHostID pgtype.UUID `json:"primary_host_id"`
	Term          int64       `json:"term"`
	ExpectedEpoch int64       `json:"expected_epoch"`
}

// Grant the next epoch to a host, term-guarded and guarded by the epoch the promoter read
// (§12.3): a compare-and-set, not an increment. Under a blind increment every promoter gets
// an epoch, each CASes the S3 epoch object to the number *it* computed, one wins, and all of
// them have already written their own host into primary_host_id — leaving the row naming a
// host that holds neither the object nor a lease. 0 rows: stale term, missing volume, or an
// epoch that moved on.
func (q *Queries) BumpVolumeEpoch(ctx context.Context, arg BumpVolumeEpochParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpVolumeEpoch,
		arg.VolumeID,
		arg.PrimaryHostID,
		arg.Term,
		arg.ExpectedEpoch,
	)
	var current_epoch int64
	err := row.Scan(&current_epoch)
	return current_epoch, err
}

const clearVolumeParent = `-- name: ClearVolumeParent :execrows
UPDATE volumes
   SET parent_snapshot_id = NULL,
       chain_depth = 0,
       updated_at = now()
 WHERE volume_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $2
`

type ClearVolumeParentParams struct {
	VolumeID uuid.UUID `json:"volume_id"`
	Term     int64     `json:"term"`
}

// Record that a volume descends from nothing any more, term-guarded: the one write
// CreateVolume's COALESCE deliberately forbids to a converging create, and the one a
// FLATTEN cannot do without (metadata.Store carries the reasoning). chain_depth goes with
// it in the same statement: §20.1's ceiling refuses on the depth, and a volume left at N
// would be as unclonable as before the copy it just paid for. No state predicate and no
// descendant check — the link it clears is one the descriptor has already stopped
// carrying, and clearing twice affects one row both times.
func (q *Queries) ClearVolumeParent(ctx context.Context, arg ClearVolumeParentParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearVolumeParent, arg.VolumeID, arg.Term)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createVolume = `-- name: CreateVolume :execrows
WITH valid AS (
    SELECT 1 FROM control_plane_leader WHERE singleton AND term = $18
)
INSERT INTO volumes (volume_id, size_bytes, block_size, rpo_target_seconds, current_epoch, state,
                     dek_wrapped, kek_id, dek_key_id, primary_host_id, standby_host_id,
                     chain_depth, parent_snapshot_id)
SELECT $1, $2, $3, $11::int, $4, $5, $6, $7, $12::bigint, $8, $9, $10,
       $13::uuid
WHERE EXISTS (SELECT 1 FROM valid)
  -- The capacity bound, as a predicate of the write that places the volume (ADR-0017): a
  -- clone admitted by a pure placement.Choose against a fleet read another operation shared
  -- lands here, against the derived value, and affects 0 rows. A write with no bound is not
  -- a placement decision — rebuild-metadata records volumes that already occupy the host.
  -- Two ceilings, because they answer different questions (placement.Policy.Admits carries
  -- the reasoning): §28.2 bounds what the host was *promised*, ADR-0013 what it reported
  -- *using*. The measured arm charges bound_add_bytes nothing on purpose, and reads the
  -- column rather than a caller's copy so the freshest heartbeat wins. A bound naming an
  -- unregistered host admits nothing: no view row, a NULL comparison, no write.
  AND ($14::uuid IS NULL
       OR (EXISTS (SELECT 1 FROM hosts
                    WHERE host_id = $14::uuid
                      AND nvme_used_bytes <= $15::bigint)
           AND (SELECT c.committed_bytes FROM host_committed_bytes c
                 WHERE c.host_id = $14::uuid)
               + $16::bigint <= $17::bigint))
ON CONFLICT (volume_id) DO UPDATE
  SET size_bytes = GREATEST(volumes.size_bytes, EXCLUDED.size_bytes),
      block_size = EXCLUDED.block_size,
      -- Overwritten like block_size and not GREATEST-ed like the watermarks: an RPO is
      -- a promise somebody set, and a lowered one is a promise being tightened. Keeping
      -- the higher value would make a target impossible to reduce.
      rpo_target_seconds = EXCLUDED.rpo_target_seconds,
      current_epoch = GREATEST(volumes.current_epoch, EXCLUDED.current_epoch),
      dek_wrapped = EXCLUDED.dek_wrapped,
      kek_id = EXCLUDED.kek_id,
      -- The three key columns move together or not at all: a wrapped DEK paired with
      -- another DEK's version is a volume nothing can open.
      dek_key_id = EXCLUDED.dek_key_id,
      primary_host_id = COALESCE(volumes.primary_host_id, EXCLUDED.primary_host_id),
      standby_host_id = COALESCE(volumes.standby_host_id, EXCLUDED.standby_host_id),
      chain_depth = EXCLUDED.chain_depth,
      -- Never cleared by a converging write: a clone that lost its parent link reads
      -- zeros, and rebuild-metadata's re-INSERT must not be able to cause that.
      parent_snapshot_id = COALESCE(volumes.parent_snapshot_id, EXCLUDED.parent_snapshot_id),
      updated_at = now()
`

type CreateVolumeParams struct {
	VolumeID         uuid.UUID   `json:"volume_id"`
	SizeBytes        int64       `json:"size_bytes"`
	BlockSize        int32       `json:"block_size"`
	CurrentEpoch     int64       `json:"current_epoch"`
	State            string      `json:"state"`
	DekWrapped       []byte      `json:"dek_wrapped"`
	KekID            string      `json:"kek_id"`
	PrimaryHostID    pgtype.UUID `json:"primary_host_id"`
	StandbyHostID    pgtype.UUID `json:"standby_host_id"`
	ChainDepth       int32       `json:"chain_depth"`
	RpoTargetSeconds int32       `json:"rpo_target_seconds"`
	DekKeyID         int64       `json:"dek_key_id"`
	ParentSnapshotID pgtype.UUID `json:"parent_snapshot_id"`
	BoundHost        pgtype.UUID `json:"bound_host"`
	BoundUsedLimit   int64       `json:"bound_used_limit"`
	BoundAddBytes    int64       `json:"bound_add_bytes"`
	BoundLimit       int64       `json:"bound_limit"`
	Term             int64       `json:"term"`
}

// Term-guarded create (§7). current_epoch is normally 0 for new volumes but is set
// by rebuild-metadata (§22.5) from the authoritative S3 epoch object.
//
// The conflict path is what makes rebuild-metadata safe to run twice, or from two
// operators at once: both see ErrNotFound for the same volume and both INSERT, and
// the loser must converge instead of aborting with 23505 after having written an
// arbitrary prefix of the catalog. It converges *without regressing*: the epoch
// (the fencing token), the size (§3 is grow-only), the watermarks and the ownership
// columns keep the higher/existing value, and `state` is not touched at all — the
// §7 lifecycle moves only through SetVolumeState.
func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (int64, error) {
	result, err := q.db.Exec(ctx, createVolume,
		arg.VolumeID,
		arg.SizeBytes,
		arg.BlockSize,
		arg.CurrentEpoch,
		arg.State,
		arg.DekWrapped,
		arg.KekID,
		arg.PrimaryHostID,
		arg.StandbyHostID,
		arg.ChainDepth,
		arg.RpoTargetSeconds,
		arg.DekKeyID,
		arg.ParentSnapshotID,
		arg.BoundHost,
		arg.BoundUsedLimit,
		arg.BoundAddBytes,
		arg.BoundLimit,
		arg.Term,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVolume = `-- name: DeleteVolume :execrows
WITH doomed AS (
    SELECT v.volume_id
      FROM volumes v
     WHERE v.volume_id = $1
       AND (SELECT term FROM control_plane_leader WHERE singleton) = $2
       AND NOT EXISTS (SELECT 1 FROM volumes d
                        WHERE d.volume_id <> $1
                          AND d.parent_snapshot_id IN (SELECT s.snapshot_id FROM snapshots s
                                                        WHERE s.volume_id = $1))
       AND NOT EXISTS (SELECT 1 FROM snapshots d
                        WHERE d.volume_id <> $1
                          AND d.parent_snapshot_id IN (SELECT s.snapshot_id FROM snapshots s
                                                        WHERE s.volume_id = $1))
), gone AS (
    DELETE FROM snapshots WHERE volume_id IN (SELECT volume_id FROM doomed)
)
DELETE FROM volumes WHERE volume_id IN (SELECT volume_id FROM doomed)
`

type DeleteVolumeParams struct {
	VolumeID uuid.UUID `json:"volume_id"`
	Term     int64     `json:"term"`
}

// Remove a volume and its snapshots, term-guarded. There is no DELETING state and no
// expiry column: the recovery window is the bucket's own versioning plus its lifecycle
// policy, and a second window here would drift from the one that controls the bytes.
//
// One statement, three parts, ordered by the two foreign keys that make volumes and
// snapshots mutually referencing:
//
//   - `doomed` is the guard — the term, and nothing descending from this volume's
//     snapshots in *either* direction (volumes.parent_snapshot_id and
//     snapshots.parent_snapshot_id, both indexed for exactly this). It selects rather
//     than deletes, so an unmet guard writes nothing at all.
//   - the snapshots go: a snapshot row whose volume is gone is unreadable, its manifest
//     living under the volume's prefix.
//   - the volume goes last.
//
// Data-modifying CTEs run to completion whether or not the primary query reads them, and
// referential integrity is checked at the end of the statement, so the two deletes are one
// atomic act. Rejected: ON DELETE CASCADE on snapshots.volume_id — a cascade is a rule
// nobody reads until it has fired, and this is the only statement that may remove a volume.
func (q *Queries) DeleteVolume(ctx context.Context, arg DeleteVolumeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVolume, arg.VolumeID, arg.Term)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVolume = `-- name: GetVolume :one
SELECT volume_id, size_bytes, block_size, rpo_target_seconds, current_epoch, state, primary_host_id, standby_host_id, chain_depth, parent_snapshot_id, dek_wrapped, kek_id, dek_key_id, commit_age_seconds, unpublished_local_bytes, reported_at, refusal, refusal_detail, fencing_started_at, created_at, updated_at FROM volumes WHERE volume_id = $1
`

func (q *Queries) GetVolume(ctx context.Context, volumeID uuid.UUID) (*Volume, error) {
	row := q.db.QueryRow(ctx, getVolume, volumeID)
	var i Volume
	err := row.Scan(
		&i.VolumeID,
		&i.SizeBytes,
		&i.BlockSize,
		&i.RpoTargetSeconds,
		&i.CurrentEpoch,
		&i.State,
		&i.PrimaryHostID,
		&i.StandbyHostID,
		&i.ChainDepth,
		&i.ParentSnapshotID,
		&i.DekWrapped,
		&i.KekID,
		&i.DekKeyID,
		&i.CommitAgeSeconds,
		&i.UnpublishedLocalBytes,
		&i.ReportedAt,
		&i.Refusal,
		&i.RefusalDetail,
		&i.FencingStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listVolumes = `-- name: ListVolumes :many
SELECT volume_id, size_bytes, block_size, rpo_target_seconds, current_epoch, state, primary_host_id, standby_host_id, chain_depth, parent_snapshot_id, dek_wrapped, kek_id, dek_key_id, commit_age_seconds, unpublished_local_bytes, reported_at, refusal, refusal_detail, fencing_started_at, created_at, updated_at FROM volumes ORDER BY volume_id
`

// Every volume, placed or not, for a human reading the catalog: a NULL primary matches no
// host id, so the per-host listings union to "everything already being served", and after
// rebuild-metadata that union is empty. Ordered by the primary key — index scan, no sort.
func (q *Queries) ListVolumes(ctx context.Context) ([]*Volume, error) {
	rows, err := q.db.Query(ctx, listVolumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.VolumeID,
			&i.SizeBytes,
			&i.BlockSize,
			&i.RpoTargetSeconds,
			&i.CurrentEpoch,
			&i.State,
			&i.PrimaryHostID,
			&i.StandbyHostID,
			&i.ChainDepth,
			&i.ParentSnapshotID,
			&i.DekWrapped,
			&i.KekID,
			&i.DekKeyID,
			&i.CommitAgeSeconds,
			&i.UnpublishedLocalBytes,
			&i.ReportedAt,
			&i.Refusal,
			&i.RefusalDetail,
			&i.FencingStartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumesByHost = `-- name: ListVolumesByHost :many
SELECT volume_id, size_bytes, block_size, rpo_target_seconds, current_epoch, state, primary_host_id, standby_host_id, chain_depth, parent_snapshot_id, dek_wrapped, kek_id, dek_key_id, commit_age_seconds, unpublished_local_bytes, reported_at, refusal, refusal_detail, fencing_started_at, created_at, updated_at FROM volumes WHERE primary_host_id = $1 ORDER BY volume_id
`

// The volumes a drain must evacuate (§28.1), in a deterministic order.
func (q *Queries) ListVolumesByHost(ctx context.Context, primaryHostID pgtype.UUID) ([]*Volume, error) {
	rows, err := q.db.Query(ctx, listVolumesByHost, primaryHostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.VolumeID,
			&i.SizeBytes,
			&i.BlockSize,
			&i.RpoTargetSeconds,
			&i.CurrentEpoch,
			&i.State,
			&i.PrimaryHostID,
			&i.StandbyHostID,
			&i.ChainDepth,
			&i.ParentSnapshotID,
			&i.DekWrapped,
			&i.KekID,
			&i.DekKeyID,
			&i.CommitAgeSeconds,
			&i.UnpublishedLocalBytes,
			&i.ReportedAt,
			&i.Refusal,
			&i.RefusalDetail,
			&i.FencingStartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordVolumeReport = `-- name: RecordVolumeReport :execrows

UPDATE volumes
   SET refusal = $1::text,
       -- One statement, so the two can never disagree: an explanation with nothing to
       -- explain is what volumes_refusal_detail_needs_a_refusal refuses outright.
       refusal_detail = CASE WHEN $1::text = ''
                            THEN '' ELSE $2::text END,
       commit_age_seconds = $3::int,
       unpublished_local_bytes = $4::bigint,
       reported_at = now(),
       updated_at = now()
 WHERE volume_id = $5
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $6
   AND primary_host_id = $7::uuid
   AND current_epoch = $8
`

type RecordVolumeReportParams struct {
	Refusal               string    `json:"refusal"`
	RefusalDetail         string    `json:"refusal_detail"`
	CommitAgeSeconds      int32     `json:"commit_age_seconds"`
	UnpublishedLocalBytes int64     `json:"unpublished_local_bytes"`
	VolumeID              uuid.UUID `json:"volume_id"`
	Term                  int64     `json:"term"`
	HostID                uuid.UUID `json:"host_id"`
	Epoch                 int64     `json:"epoch"`
}

// There is no ResizeVolume query. It was here, it was grow-only and term-guarded, and
// nothing but a contract test ever ran it: V1 has no resize, because the row is the only
// half of it that existed (see metadata.Store, where the method was). No statement in
// this file writes size_bytes after CreateVolume, and that is what makes the geometry the
// Agent and descriptor.json were handed at create still true when they are read back.
// One report from one host, recorded in one statement: how far behind the object store the
// volume is, how much would be lost with the host, and whether the host is serving it at
// all. They are one write because they are one observation, and splitting them would let a
// volume render as behind and serving, or as refused and current, out of two rounds.
//
// Term-guarded like every other mutation and — unlike every other one — qualified by the
// *reporting* host and epoch. Without that predicate a host the fleet has moved past would
// mark a volume NOT SERVED while its successor serves it, and would stamp its own RPO over
// the successor's; the term guard does not catch it, because promotion does not change the
// CP term. 0 rows is therefore normal, and means the reporter is not the writer any more.
//
// Last-report-wins and not a monotonic merge. The three columns the watermarks left behind
// were merged with GREATEST because they only ever grew; an age and a backlog both shrink
// when a commit lands, and a max over them would freeze the row at the worst moment the
// volume ever had.
func (q *Queries) RecordVolumeReport(ctx context.Context, arg RecordVolumeReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordVolumeReport,
		arg.Refusal,
		arg.RefusalDetail,
		arg.CommitAgeSeconds,
		arg.UnpublishedLocalBytes,
		arg.VolumeID,
		arg.Term,
		arg.HostID,
		arg.Epoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVolumePrimaryHost = `-- name: SetVolumePrimaryHost :execrows
UPDATE volumes
   SET primary_host_id = $1::uuid,
       state = CASE WHEN $1::uuid IS NULL
                    THEN 'DETACHED' ELSE 'ACTIVE' END,
       fencing_started_at = NULL,
       refusal = '',
       refusal_detail = '',
       commit_age_seconds = NULL,
       unpublished_local_bytes = 0,
       reported_at = NULL,
       updated_at = now()
 WHERE volume_id = $2
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $3
   AND state = ANY($4::text[])
   AND (primary_host_id IS NULL
        OR $1::uuid IS NULL
        OR primary_host_id = $1::uuid)
`

type SetVolumePrimaryHostParams struct {
	PrimaryHostID pgtype.UUID `json:"primary_host_id"`
	VolumeID      uuid.UUID   `json:"volume_id"`
	Term          int64       `json:"term"`
	AllowedStates []string    `json:"allowed_states"`
}

// Place a volume on a host, or clear its placement (a NULL primary_host_id),
// term-guarded. It is the only write of primary_host_id that is not a promotion:
// CreateVolume's conflict path protects the column with COALESCE, so before this query an
// attach was permanent. The state moves with the ownership in this statement because they
// are one fact; two writes have a window, and a volume left ACTIVE with no host is one a
// snapshot request accepts and no Agent can ever take.
//
// Three predicates, each refusing something different: the CP term (§7); `state = ANY(...)`,
// the §7 transition table as a predicate, in SQL so a read-modify-write cannot be split by
// a second Control Plane; and the placement guard, which refuses only the straight
// hand-over A -> B, since a host discovers it has lost a volume on its next poll.
//
// fencing_started_at and everything the departing host reported are cleared for the same
// reason: none of it is true of a volume that has just changed hands, and a dwell, an
// explanation or an RPO left behind would be inherited by the next promotion or printed
// against a host that is serving fine.
func (q *Queries) SetVolumePrimaryHost(ctx context.Context, arg SetVolumePrimaryHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVolumePrimaryHost,
		arg.PrimaryHostID,
		arg.VolumeID,
		arg.Term,
		arg.AllowedStates,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVolumeState = `-- name: SetVolumeState :execrows
UPDATE volumes
   SET state = $2,
       fencing_started_at = CASE
           WHEN $2 <> 'FENCING_WAIT'            THEN NULL
           WHEN fencing_started_at IS NOT NULL   THEN fencing_started_at
           ELSE now()
       END,
       updated_at = now()
 WHERE volume_id = $1
   AND (SELECT term FROM control_plane_leader WHERE singleton) = $3
   AND state = ANY($4::text[])
`

type SetVolumeStateParams struct {
	VolumeID      uuid.UUID `json:"volume_id"`
	State         string    `json:"state"`
	Term          int64     `json:"term"`
	AllowedStates []string  `json:"allowed_states"`
}

// The §7 ownership machine, term-guarded and transition-guarded: $4 is the set of states
// that may legally become $2, taken from the lifecycle table. In the predicate rather than
// in Go so two Control Planes reacting to the same suspicion cannot both win a
// read-modify-write.
//
// It also stamps the fence-start instant (ADR-0015), in the same write. Entering
// FENCING_WAIT with nothing recorded starts the dwell by *this* database's clock — the one
// last_renewal is stamped by (§12.1); entering it again does not move the instant, or a
// resumable promotion would push its own deadline forward on every pass; leaving it clears
// the record, so the next promotion waits its own dwell.
func (q *Queries) SetVolumeState(ctx context.Context, arg SetVolumeStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVolumeState,
		arg.VolumeID,
		arg.State,
		arg.Term,
		arg.AllowedStates,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
